# https://goreleaser.com/actions/
on:
  push:
    tags:
      - 'v*'
name: GoReleaser
jobs:
  test:
    name: test
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
      - name: install go
        uses: actions/setup-go@v1
        with:
          go_version: '1.13.4'
      - name: checkout code
        uses: actions/checkout@master
      - name: run tests
        run: go test -v ./...
  release:
    name: release
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - name: checkout code
      uses: actions/checkout@master
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release
      if: success()
