# https://goreleaser.com/actions/
on:
  push:
    tags:
      - 'v*'
name: GoReleaser
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    #needs: [ test ]
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go_version: '1.13.4'
    - name: Checkout code
      uses: actions/checkout@master
    - name: Run tests
      run: go test -v ./...
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release
      if: success()
